# Generated by Django 3.2.9 on 2021-11-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzdevumi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='reason',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='date_time',
        ),
    ]
