# Generated by Django 3.2.9 on 2021-11-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzdevumi', '0003_rename_visitor_visit_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='User',
        ),
    ]
